---
title: "Independent Samples T Test"
output: pdf_document
params:
  descr: NA
  results1: NA
  results2: NA
  d: NA
  l: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(ft.tabcolsep=0, ft.latex.float = "none")
knitr::opts_chunk$set(comment = NA)
library(shiny)
library(dplyr)
library(knitr)
library(rempsyc)
library(flextable)
library(broom)
library(purrr)
set_flextable_defaults(fonts_ignore = TRUE)
```

## Independent Samples T Test

### Two-Sample Statistics

```{r}
kable(params$descr)
```

### Levene's Test for Equality of Variances
```{r}
kable(params$l)
```


### Two-Sample Test
#### Equal Variances Assumed

```{r}
df1 <- map_df(list(params$results1), tidy)
df1 <- df1[c("estimate", "statistic", "p.value", "conf.low", "conf.high")]
colnames(df1) <- c("Estimate", "t", "p value", "Conf.Int.Low", "Conf.Int.High")
kable(df1)
```

#### Equal Variances Not Assumed

```{r}
df2 <- map_df(list(params$results2), tidy)
df2 <- df2[c("estimate", "statistic", "p.value", "conf.low", "conf.high")]
colnames(df2) <- c("Estimate", "t", "p value", "Conf.Int.Low", "Conf.Int.High")
kable(df2)
```

### Effect Sizes
```{r}
kable(params$d)
```
