---
title: "Repeated Measures ANOVA"
output: pdf_document
params:
  descr: NA
  levene: NA
  welch: NA
  anova: NA
  n2: NA
  em: NA
  posthoc: NA
  se: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(ft.tabcolsep=0, ft.latex.float = "none")
library(shiny)
library(dplyr)
library(knitr)
library(rempsyc)
library(flextable)
set_flextable_defaults(fonts_ignore = TRUE)
```

## Repeated Measures ANOVA

### Descriptives
```{r, results='asis'}
if (params$descr != "Not Calculated") {
  for(x in params$descr) print(kable(x))
}
```

### Levene's Test for Homogeneity of Variances
```{r}
if (params$levene != "Not Calculated") {
  kable(params$levene)
}
```

### Welch Test
```{r}
if (params$welch != "Not Calculated") {
  kable(params$welch)
}
```

### Analysis of Variance Table
```{r}
kable(params$anova)
```

### Effect Sizes
```{r}
if (params$n2 != "Not Calculated") {
  kable(params$n2)
}
```

### Estimated Marginal Means
```{r}
if (params$em != "Not Calculated") {
  summary(params$em)
}
```

### Pairwise Comparisons
```{r}
if (params$posthoc != "Not Calculated") {
  params$posthoc
}
```

### Test for Simple Effects
```{r}
if (params$se != "Not Calculated") {
  params$se
}
```